name: "Multi event pipline workflow"
on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master



jobs:
  hey_pipeline:
    if: github.event_name == 'hey_pipeline' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master / test push"
        run: echo "Running on master or test branch push"

      - name: Print current date
        run: date  

   on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"

  
