name: "Multi event pipline workflow"
on:
  push:
    branches:
      - master
      - test

jobs:
  hey_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master / test push"
        run: echo "Running on master or test branch push"

      - name: Print current date
        run: date  


