name: "Multi event pipline workflow"
on:
  push:
    branches:
      - master
      - test

jobs:
  hey_pipeline:
  pull_request:
    branches:
      - master
    
     workflow_dispatch: # Allows manual triggering of the workflow



jobs:
  hey_pipeline:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master / test push"
        run: echo "Running on master or test branch push"

      - name: Print current date
        run: date
        
  on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"

  on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on manual trigger"
        run: echo "Running on manual trigger"
      
